### PR TITLE
Workaround to handle incorrect Oura API readiness data

### PR DESCRIPTION
**Pull request by pierretamisier**
This PR fixes https://github.com/ethanopp/fitly/issues/3

### CODE REVIEW

**Comment by ethanopp** [comment]
@pierretamisier Does this only happen with readiness, or can it happen on activity and sleep data as well?

**Comment by pierretamisier** [comment]
Sorry, I should have stated, "this piece of code fixes the issue I encountered with the Oura API" when retrieving some days of *readiness* data only. 😅 No probs with sleep or activity. (see issue #3 I raised)
I'm still waiting on the Oura devs to get back to me (the helpdesk told me they forwarded the Github issue link to the devs) on why the API returns 2 entries for readiness on random report dates. I published this PR as a workaround for those who are facing the same problem. I don't think it should be merged into master yet until we get a word from Oura at least.

> Do we know that the first record will always be the bad one?

Based on my analysis of all the bad entries I received, the first one is always the bad one.

**Comment by ethanopp** [comment]
Okay cool will wait on oura teams response before merging

**Comment by ethanopp** [comment]
Hey @pierretamisier do we still need this? I think I incorporated some of the code changes manually while we were waiting to hear back from oura support, so curious if master branch has resolved the issue or still need to merge this

**Comment by pierretamisier** [comment]
Oura closed my ticket and never got back to me I'm afraid.

**Comment by ethanopp** [comment]
...interesting - I believe we resolved the base issue in https://github.com/ethanopp/fitly/issues/3 so going to close this... reopen if there’s something else that still needs merging

**Comment by ethanopp** [comment]
Addressed in https://github.com/ethanopp/fitly/commit/1915253d9621e9a4dff83d4fa448d9354de511d3

**Pull request closed without merging**
